apiVersion: apps/v1
kind: Deployment
metadata:
  name: mor-assigmnet
  namespace: default
spec:
  selector:
    matchLabels:
      app: mor-assigmnet
  replicas: 3
  template:
    metadata:
      labels:
        app: mor-assigmnet
    spec:
      containers:
      - name: python-hw
        image: morbendor/2bcloud_assignment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mor-assigmnet-svc
  labels:
    app: mor-assigmnet
spec:
  selector:
    app: mor-assigmnet
  type: NodePort
  ports:
  - nodePort: 30222
    port: 8081
    targetPort: 8081

#minikube service mor-assigmnet-svc --url#